version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/sstarcher/helm-release
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: git submodule update --init --recursive --remote
      - run: go test -v ./...
